apiVersion: v1
kind: Service
metadata:
  name: {{ include "boiler-telemetry.fullname" . }}-anomaly-service
  labels:
    {{- include "boiler-telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: anomaly-service
spec:
  type: ClusterIP
  selector:
    {{- include "boiler-telemetry.selectorLabels" (dict "component" "anomaly-service" "root" .) | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: {{ .Values.anomalyService.port }}
