apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init
  labels:
    {{- include "boiler-telemetry.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        app: kafka-topic-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-topics
          image: apache/kafka:3.7.0
          command:
            - sh
            - -c
            - |
              echo "waiting for kafka..."
              until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1; do
                sleep 3
              done
              echo "creating topics with RF=3, min.insync.replicas=2..."
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists \
                --topic telemetry-events --partitions 3 --replication-factor 3 \
                --config min.insync.replicas=2
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists \
                --topic anomaly-events --partitions 3 --replication-factor 3 \
                --config min.insync.replicas=2
              echo "done"
              /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --describe
